import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import fetchBooks from "@/lib/fetchBooks";

const notoSansKR = Noto_Sans_KR({
  variable: "--font-noto-sans-kr",
  subsets: ["latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Footer = async () => {
  const url = `${process.env.API_SERVER_URL}/book`;

  try {
    const response = await fetch(url, { cache: 'no-store' });

    if (!response.ok) {
      return (
        <footer>
          <div>도서를 불러오는 중 오류가 발생했습니다.</div>
        </footer>
      )
    }

    const data = await response.json();
    return (
      <footer>
        <div>
          {data.length} 개의 도서가 등록되어 있습니다.
        </div>
      </footer>
    );
  } catch (error) {
    console.error('Error fetching books:', error);
    return (
      <footer>
        <div>도서를 불러오는 중 오류가 발생했습니다.</div>
      </footer>
    );
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSansKR.variable} antialiased bg-gray-50`}
      >
        <div className="w-[600px] mx-auto my-0 h-full min-h-screen flex flex-col shadow-2xl">
          <header className="w-full h-16 flex items-center justify-start px-4 gap-2">
            <Link href="/">📚 띨리의 서재</Link>
          </header>
          <main className="grow p-4">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
