import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const notoSansKR = Noto_Sans_KR({
  variable: "--font-noto-sans-kr",
  subsets: ["latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSansKR.variable} antialiased bg-gray-50`}
      >
        <div className="w-[600px] mx-auto my-0 h-full min-h-screen flex flex-col shadow-2xl">
          <header className="w-full h-16 flex items-center justify-start px-4 gap-2">
            <Link href="/">📚 띨리의 서재</Link>
          </header>
          <main className="grow p-4">
            {children}
          </main>
          <footer className="text-left text-sm text-gray-500 w-full h-16 px-4 flex items-center justify-start">
            Copyright 2025. camomilekr. All rights reserved.
          </footer>
        </div>
      </body>
    </html>
  );
}
